spring:
  datasource:
    hikari:
      #driver-class-name: com.mysql.cj.jdbc.Driver
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      #jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 1234
      connection-test-query: SELECT NOW() FROM dual
      minimum-idle: 10
      maximum-pool-size: 100

logging:
  level:
    root: debug
    #log4jdbc 옵션 설정
    jdbc: off
    #커넥션 open close 이벤트를 로그로 남긴다.
    jdbc.connection: off
    #SQL문만을 로그로 남기며, PreparedStatement일 경우 관련된 argument 값으로 대체된 SQL문이 보여진다.
    jdbc.sqlonly: off
    #SQL문과 해당 SQL을 실행시키는데 수행된 시간 정보(milliseconds)를 포함한다.
    jdbc.sqltiming: debug
    #ResultSet을 제외한 모든 JDBC 호출 정보를 로그로 남긴다. 많은 양의 로그가 생성되므로 특별히 JDBC 문제를 추적해야 할 필요가 있는 경우를 제외하고는 사용을 권장하지 않는다.
    jdbc.audit: off
    #ResultSet을 포함한 모든 JDBC 호출 정보를 로그로 남기므로 매우 방대한 양의 로그가 생성된다.
    jdbc.resultset: off
    #SQL 결과 조회된 데이터의 table을 로그로 남긴다.
    jdbc.resultsettable: off
